### ISSUE TITLE
test MMS/GBS broken

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/BOUT-dev#1502]
Should be fixed or disabled/removed

https://omadesala.alfa1024.info/BEST/2019-01-15_20:01/

**Comment by dschwoerer** [comment]
Currently:
```
gbs.cxx: In member function ‘virtual int GBS::init(bool)’:
gbs.cxx:109:5: error: ‘string’ was not declared in this scope
     string source;
     ^~~~~~
gbs.cxx:109:5: note: suggested alternative:
In file included from /usr/include/c++/8/string:39,
                 from /usr/include/c++/8/stdexcept:39,
                 from /usr/include/c++/8/array:39,
                 from /usr/include/c++/8/tuple:39,
                 from /usr/include/c++/8/functional:54,
                 from ../../../include/bout/deriv_store.hxx:32,
                 from ../../../include/bout/mesh.hxx:49,
                 from ../../../include/globals.hxx:30,
                 from ../../../include/bout.hxx:41,
                 from ../../../include/bout/physicsmodel.hxx:40,
                 from gbs.hxx:7,
                 from gbs.cxx:15:
/usr/include/c++/8/bits/stringfwd.h:74:33: note:   ‘std::__cxx11::string’
   typedef basic_string<char>    string;
                                 ^~~~~~
gbs.cxx:110:26: error: ‘source’ was not declared in this scope
     optne->get("source", source, "0.0");
                          ^~~~~~
gbs.cxx:110:26: note: suggested alternative: ‘sort’
     optne->get("source", source, "0.0");
                          ^~~~~~
                          sort
gbs.cxx:123:5: error: ‘string’ was not declared in this scope
     string source;
     ^~~~~~
gbs.cxx:123:5: note: suggested alternative:
In file included from /usr/include/c++/8/string:39,
                 from /usr/include/c++/8/stdexcept:39,
                 from /usr/include/c++/8/array:39,
                 from /usr/include/c++/8/tuple:39,
                 from /usr/include/c++/8/functional:54,
                 from ../../../include/bout/deriv_store.hxx:32,
                 from ../../../include/bout/mesh.hxx:49,
                 from ../../../include/globals.hxx:30,
                 from ../../../include/bout.hxx:41,
                 from ../../../include/bout/physicsmodel.hxx:40,
                 from gbs.hxx:7,
                 from gbs.cxx:15:
/usr/include/c++/8/bits/stringfwd.h:74:33: note:   ‘std::__cxx11::string’
   typedef basic_string<char>    string;
                                 ^~~~~~
gbs.cxx:124:26: error: ‘source’ was not declared in this scope
     optte->get("source", source, "0.0");
                          ^~~~~~
gbs.cxx:124:26: note: suggested alternative: ‘sort’
     optte->get("source", source, "0.0");
                          ^~~~~~
                          sort
gbs.cxx:251:27: warning: this statement may fall through [-Wimplicit-fallthrough=]
     logB = log(coords->Bxy);
                           ^
gbs.cxx:253:3: note: here
   default:
   ^~~~~~~
make: *** [../../../make.config:304: gbs.o] Error 1
rm: cannot remove 'mms-slab2d/BOUT.dmp.*.nc': No such file or directory
/usr/lib64/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
getmpirun: using the default mpirun -np
Making MMS test
Running with -d mms-slab2d mesh:nx=18 mesh:dx=0.00016 MZ=16
Traceback (most recent call last):
  File "./runtest-slab2d", line 49, in <module>
    s, out = launch_safe(cmd, runcmd=MPIRUN, nproc=nproc, pipe=True)
  File "/home/bout-test/tmp.i6YN366nkJ/tools/pylib/boututils/run_wrapper.py", line 275, in launch_safe
    (s,command,out))
RuntimeError: Run failed with 255.
Command was:
./gbs -d mms-slab2d mesh:nx=18 mesh:dx=0.00016 MZ=16
```

After that, a 2nd y guard cell is required.

Really issue:
3d doesn't converge

**Comment by dschwoerer** [comment]
with std::string and 2nd guard cell, I get the following convergence plot (after ~ 24 hours, still running)

![gbs3d_converge](https://user-images.githubusercontent.com/5637662/51313580-d3ccf100-1a45-11e9-9e84-02a8f6a13ee6.png)
