### ISSUE TITLE
SEGV when OpenMP is enabled

### ISSUE THREAD

**Issue by yurivict** [boutproject/BOUT-dev#2620]
SEGVs are in fftw code:
```
Thread 6 received signal SIGSEGV, Segmentation fault.
Address not mapped to object.
[Switching to LWP 788549 of process 72798]
0x00000008025bf4b0 in fftw_execute () from /usr/local/lib/libfftw3.so.3
(gdb) bt
#0  0x00000008025bf4b0 in fftw_execute () from /usr/local/lib/libfftw3.so.3
#1  0x0000000800d39115 in bout::fft::DST (in=0x84c138148, length=158, out=0x84d80e000) at /usr/ports/science/bout++/work/BOUT-dev-4.4.2/src/invert/fft_fftw.cxx:425
#2  0x0000000800d51083 in DST (in=0x84c138148, length=158, out=0x84d80e000) at /usr/ports/science/bout++/work/BOUT-dev-4.4.2/include/fft.hxx:128
#3  0x0000000800d4ddd4 in .omp_outlined._debug__.83(LaplaceCyclic *, const int &, const int &, int &, int &, int &, const Field3D &, const Field3D &, Matrix<std::__1::complex<double> > &, co
nst int &, Matrix<std::__1::complex<double> > &, Matrix<std::__1::complex<double> > &, Matrix<std::__1::complex<double> > &) const (.global_tid.=0x7fffcfff4d60, .bound_tid.=0x7fffcfff4d58, 
    this=0x80a63ac00, nxny=@0x7fffffffe018: 84, ny=@0x7fffffffe020: 1, ys=@0x7fffffffe024: 0, inbndry=@0x7fffffffe02c: 2, outbndry=@0x7fffffffe028: 2, x0=..., rhs=..., bcmplx3D=...,
    nsys=@0x7fffffffe01c: 158, a3D=..., b3D=..., c3D=...) at /usr/ports/science/bout++/work/BOUT-dev-4.4.2/src/invert/laplace/impls/cyclic/cyclic_laplace.cxx:334
#4  0x0000000800d4e2ed in .omp_outlined..84(void) const (.global_tid.=0x7fffcfff4d60, .bound_tid.=0x7fffcfff4d58, this=0x80a63ac00, nxny=@0x7fffffffe018: 84, ny=@0x7fffffffe020: 1,
    ys=@0x7fffffffe024: 0, inbndry=@0x7fffffffe02c: 2, outbndry=@0x7fffffffe028: 2, x0=..., rhs=..., bcmplx3D=..., nsys=@0x7fffffffe01c: 158, a3D=..., b3D=..., c3D=...)
    at /usr/ports/science/bout++/work/BOUT-dev-4.4.2/src/invert/laplace/impls/cyclic/cyclic_laplace.cxx:313
#5  0x00000008027035d3 in __kmp_invoke_microtask () at /disk-samsung/freebsd-src/contrib/llvm-project/openmp/runtime/src/z_Linux_asm.S:1166
#6  0x00000008026d7262 in __kmp_invoke_task_func (gtid=5) at /disk-samsung/freebsd-src/contrib/llvm-project/openmp/runtime/src/kmp_runtime.cpp:7559
#7  0x00000008026d61fd in __kmp_launch_thread (this_thr=0x80a6e4640) at /disk-samsung/freebsd-src/contrib/llvm-project/openmp/runtime/src/kmp_runtime.cpp:6020
#8  0x000000080270420c in __kmp_launch_worker (thr=0x80a6e4640) at /disk-samsung/freebsd-src/contrib/llvm-project/openmp/runtime/src/z_Linux_util.cpp:527
#9  0x00000008002f8a6a in thread_start (curthread=0x80a614300) at /disk-samsung/freebsd-src/lib/libthr/thread/thr_create.c:292
#10 0x0000000000000000 in ?? ()
```

clang-14
FreeBSD 13.1

**Comment by dschwoerer** [comment]
What physics model is that from? Or do you have a way to reproduce that?
I assume that is the 4.4.2 release?

**Comment by dschwoerer** [comment]
It has been a while without feedback. Closing for now. Feel free to reopen with additional details.
