### ISSUE TITLE
Build breaks: KeyError: 'true'

### ISSUE THREAD

**Issue by yurivict** [boutproject/BOUT-dev#2758]
```
[ 93% 146/152] cd /usr/ports/science/bout++/work/BOUT-dev-5.1.0/tools/pylib/_boutpp_build && /usr/local/bin/cmake -E make_directory /usr/ports/science/bout++/work/.build/tools/pylib/_boutpp_build && /usr/local/bin/cmake -E env PYTHONPATH=/usr/ports/science/bout++/work/.build/tools/pylib/_boutpp_build/..: /usr/local/bin/python3.9 generate.py helper.h.jinja /usr/ports/science/bout++/work/.build/tools/pylib/_boutpp_build/helper.h
FAILED: tools/pylib/_boutpp_build/helper.h /usr/ports/science/bout++/work/.build/tools/pylib/_boutpp_build/helper.h
cd /usr/ports/science/bout++/work/BOUT-dev-5.1.0/tools/pylib/_boutpp_build && /usr/local/bin/cmake -E make_directory /usr/ports/science/bout++/work/.build/tools/pylib/_boutpp_build && /usr/local/bin/cmake -E env PYTHONPATH=/usr/ports/science/bout++/work/.build/tools/pylib/_boutpp_build/..: /usr/local/bin/python3.9 generate.py helper.h.jinja /usr/ports/science/bout++/work/.build/tools/pylib/_boutpp_build/helper.h
Traceback (most recent call last):
  File "/usr/ports/science/bout++/work/BOUT-dev-5.1.0/tools/pylib/_boutpp_build/generate.py", line 5, in <module>
    from boutconfig import config as conf
  File "/usr/ports/science/bout++/work/.build/tools/pylib/boutconfig/__init__.py", line 54, in <module>
    has[k[4:]] = _yesno[config[k]]
KeyError: 'true'
[ 94% 146/152] cd /usr/ports/science/bout++/work/BOUT-dev-5.1.0/tools/pylib/_boutpp_build && /usr/local/bin/cmake -E make_directory /usr/ports/science/bout++/work/.build/tools/pylib/_boutpp_build && /usr/local/bin/cmake -E env PYTHONPATH=/usr/ports/science/bout++/work/.build/tools/pylib/_boutpp_build/..: /usr/local/bin/python3.9 generate.py helper.cxx.jinja /usr/ports/science/bout++/work/.build/tools/pylib/_boutpp_build/helper.cxx
FAILED: tools/pylib/_boutpp_build/helper.cxx /usr/ports/science/bout++/work/.build/tools/pylib/_boutpp_build/helper.cxx
cd /usr/ports/science/bout++/work/BOUT-dev-5.1.0/tools/pylib/_boutpp_build && /usr/local/bin/cmake -E make_directory /usr/ports/science/bout++/work/.build/tools/pylib/_boutpp_build && /usr/local/bin/cmake -E env PYTHONPATH=/usr/ports/science/bout++/work/.build/tools/pylib/_boutpp_build/..: /usr/local/bin/python3.9 generate.py helper.cxx.jinja /usr/ports/science/bout++/work/.build/tools/pylib/_boutpp_build/helper.cxx
Traceback (most recent call last):
  File "/usr/ports/science/bout++/work/BOUT-dev-5.1.0/tools/pylib/_boutpp_build/generate.py", line 5, in <module>
    from boutconfig import config as conf
  File "/usr/ports/science/bout++/work/.build/tools/pylib/boutconfig/__init__.py", line 54, in <module>
    has[k[4:]] = _yesno[config[k]]
KeyError: 'true'
[ 94% 146/152] cd /usr/ports/science/bout++/work/BOUT-dev-5.1.0/tools/pylib/_boutpp_build && /usr/local/bin/cmake -E make_directory /usr/ports/science/bout++/work/.build/tools/pylib/_boutpp_build && /usr/local/bin/cmake -E env PYTHONPATH=/usr/ports/science/bout++/work/.build/tools/pylib/_boutpp_build/..: /usr/local/bin/python3.9 generate.py boutcpp.pxd.jinja /usr/ports/science/bout++/work/.build/tools/pylib/_boutpp_build/boutcpp.pxd
FAILED: tools/pylib/_boutpp_build/boutcpp.pxd /usr/ports/science/bout++/work/.build/tools/pylib/_boutpp_build/boutcpp.pxd
cd /usr/ports/science/bout++/work/BOUT-dev-5.1.0/tools/pylib/_boutpp_build && /usr/local/bin/cmake -E make_directory /usr/ports/science/bout++/work/.build/tools/pylib/_boutpp_build && /usr/local/bin/cmake -E env PYTHONPATH=/usr/ports/science/bout++/work/.build/tools/pylib/_boutpp_build/..: /usr/local/bin/python3.9 generate.py boutcpp.pxd.jinja /usr/ports/science/bout++/work/.build/tools/pylib/_boutpp_build/boutcpp.pxd
Traceback (most recent call last):
  File "/usr/ports/science/bout++/work/BOUT-dev-5.1.0/tools/pylib/_boutpp_build/generate.py", line 5, in <module> 
    from boutconfig import config as conf
  File "/usr/ports/science/bout++/work/.build/tools/pylib/boutconfig/__init__.py", line 54, in <module>
    has[k[4:]] = _yesno[config[k]]
KeyError: 'true'

```

Version: 5.1.0
Python-3.9
FreeBSD 13.2

**Comment by dschwoerer** [comment]
It seems you used `cmake`. How did you configure the build?

**Comment by ZedThree** [comment]
I think it's this bit:

```Python
has = {}
for k in config:
    if k.startswith("has_"):
        has[k[4:]] = _yesno[config[k]]
```

and we want `config[k].upper()`

**Comment by dschwoerer** [comment]
I think so too :-)
I forgot to comment here, PR is here: https://github.com/boutproject/BOUT-dev/pull/2759
